# Generated by Django 4.2.17 on 2025-07-11 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jornada.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='academicos/')),
                ('titulo_grado', models.TextField(blank=True, help_text='Ingrese títulos y grados, colocando cada uno en una línea separada (deje un salto de línea entre cada uno).', verbose_name='Títulos y Grados')),
                ('especialidad', models.CharField(max_length=200)),
                ('biografia', models.TextField()),
                ('cargo', models.CharField(choices=[('Director de departamento', 'Director de departamento'), ('Director de escuela', 'Director de escuela'), ('Académico', 'Académico')], default='Académico', max_length=30)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('lineas_investigacion', models.TextField(blank=True, help_text='Ingrese las líneas de investigación, colocando cada una en una línea separada (deje un salto de línea entre cada una).', verbose_name='Líneas de Investigación')),
                ('actividades_curriculares', models.TextField(blank=True, help_text='Lista de cursos o actividades curriculares.', verbose_name='Actividades Curriculares')),
                ('otros_interes', models.TextField(blank=True, help_text='Cualquier otra información relevante.', verbose_name='Otros de Interés')),
                ('email', models.EmailField(blank=True, help_text='Ingrese el correo electrónico del académico.', max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('sitio_web', models.URLField(blank=True, help_text='Ingrese la URL de la página web del académico.', null=True, verbose_name='Página Web')),
                ('researchgate', models.URLField(blank=True, help_text='Ingrese la URL a ResearchGate.', null=True, verbose_name='ResearchGate')),
                ('orcid', models.URLField(blank=True, help_text='Ingrese la URL a ORCID.', null=True, verbose_name='ORCID')),
                ('wos', models.URLField(blank=True, help_text='Ingrese la URL a WOS.', null=True, verbose_name='WOS')),
                ('proyectos_investigacion_actuales', models.TextField(blank=True, help_text='Listado de proyectos actuales de investigación. Puede incluir HTML para formatear listas.', verbose_name='Proyectos de Investigación Actuales')),
                ('proyectos_investigacion_pasados', models.TextField(blank=True, help_text='Listado de proyectos pasados de investigación. Puede incluir HTML para formatear listas.', verbose_name='Proyectos de Investigación Pasados')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaPostgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autores', models.TextField(help_text='Lista completa de autores en formato: Apellido, Iniciales')),
                ('revista', models.CharField(blank=True, max_length=200, verbose_name='Revista / Editorial')),
                ('anio', models.PositiveIntegerField(default=2025)),
                ('mes', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True)),
                ('doi', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('Articulo', 'Artículo'), ('Libro', 'Libro'), ('Capitulo', 'Capítulo de libro'), ('Conferencia', 'Artículo en conferencia'), ('Otro', 'Otro')], default='Articulo', max_length=20)),
                ('estado', models.CharField(choices=[('en_preparacion', 'En preparación'), ('sometida', 'Sometida'), ('aceptada', 'Aceptada'), ('publicada', 'Publicada'), ('rechazada', 'Rechazada')], default='en_preparacion', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='publicaciones/')),
                ('visible', models.BooleanField(default=True)),
                ('academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='jornada.academico')),
            ],
            options={
                'ordering': ['-anio', '-mes', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(blank=True, max_length=200, null=True)),
                ('año_ingreso', models.IntegerField(blank=True, null=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_actividad', models.TextField(blank=True, verbose_name='Detalle de la actividad')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('tipo_actividad', models.CharField(choices=[('Charla', 'Charla'), ('Congreso', 'Congreso'), ('Viaje', 'Viaje'), ('Otro', 'Otro')], max_length=20, verbose_name='Tipo de actividad')),
                ('fecha_salida', models.DateTimeField(verbose_name='Fecha y hora de salida')),
                ('fecha_regreso', models.DateTimeField(verbose_name='Fecha y hora de regreso')),
                ('telefono_emergencia', models.CharField(max_length=20, verbose_name='Teléfono de emergencia')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre del archivo o descripción corta.', max_length=255)),
                ('archivo', models.FileField(blank=True, help_text='Opcional: Sube un archivo si lo deseas. Puedes proporcionar un archivo o un enlace (en el siguiente apartado).', null=True, upload_to=jornada.models.ruta_archivo)),
                ('link', models.URLField(blank=True, help_text='Opcional. Enlace a un documento externo. Puedes proporcionar un enlace o un archivo (en el apartado previo).', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del archivo.', null=True)),
                ('seccion', models.CharField(blank=True, help_text='Nombre de sección opcional del archivo.', max_length=255, null=True)),
                ('academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='jornada.academico')),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_publicados', to='jornada.asignatura')),
            ],
        ),
        migrations.AddField(
            model_name='academico',
            name='escuelas',
            field=models.ManyToManyField(blank=True, related_name='academicos', to='jornada.escuela'),
        ),
        migrations.AddField(
            model_name='academico',
            name='programas_postgrado',
            field=models.ManyToManyField(blank=True, related_name='academicos_postgrado', to='jornada.programapostgrado'),
        ),
        migrations.AddField(
            model_name='academico',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('frecuencia', models.CharField(choices=[('ninguna', 'Ninguna'), ('diaria', 'Cada día'), ('semanal', 'Cada semana el mismo día'), ('mensual_cuarto', 'Cada mes el cuarto día de la semana'), ('mensual_ultimo', 'Cada mes el último día de la semana'), ('anual', 'Anualmente en la misma fecha'), ('laboral', 'Todos los días laborables')], default='ninguna', max_length=20)),
                ('grupo_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornada.sala')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sala', 'fecha', 'hora_inicio')},
            },
        ),
    ]
