# Generated by Django 4.2.17 on 2025-07-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
