# Generated by Django 4.2.17 on 2025-07-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0002_escuela_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
