# Generated by Django 4.2.17 on 2025-07-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0003_alter_escuela_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='programapostgrado',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
