# Generated by Django 4.2.17 on 2025-07-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0004_programapostgrado_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programapostgrado',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
