# Generated by Django 4.2.17 on 2025-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0005_alter_programapostgrado_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academico',
            name='programas_postgrado',
            field=models.ManyToManyField(blank=True, related_name='academicos', to='jornada.programapostgrado'),
        ),
    ]
