# Generated by Django 4.2.17 on 2025-07-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0007_departamento_academico_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='academico',
            name='cargos',
            field=models.ManyToManyField(blank=True, related_name='academicos', to='jornada.cargo'),
        ),
    ]
