# Generated by Django 4.2.17 on 2025-07-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0008_cargo_academico_cargos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academico',
            name='cargo',
        ),
    ]
