# Generated by Django 4.2.17 on 2025-07-12 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0011_alter_aviso_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='jornada.academico'),
        ),
    ]
