# Generated by Django 4.2.17 on 2025-07-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0012_alter_aviso_academico'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='jornada.departamento'),
        ),
    ]
