# Generated by Django 4.2.17 on 2025-07-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0013_escuela_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='programapostgrado',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='jornada.departamento'),
        ),
    ]
