# Generated by Django 4.2.17 on 2025-07-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada', '0014_programapostgrado_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='honorifico',
            field=models.CharField(blank=True, choices=[('', '— Selecciona —'), ('Dr.', 'Dr.'), ('Dra.', 'Dra.'), ('Prof.', 'Prof.'), ('Profa.', 'Profa.'), ('Mg.', 'Mg.'), ('M.Sc.', 'M.Sc.'), ('M.A.', 'M.A.'), ('MBA', 'MBA'), ('PhD', 'PhD')], help_text='Cómo quiere que se refieran a usted (Dr., Dra., Ing., Mg., etc.)', max_length=10, verbose_name='Prefijo / Título'),
        ),
    ]
